GSC/Controllers/ProveedoresController.cs
using BaseDeDatos.ProveedoresFolder;
using System.Web.Mvc;

namespace GSC.Controllers
{
    [Authorize]
    public class ProveedoresController : Controller
    {
        ProveedoresData data = new ProveedoresData(); 
        // GET: Proveedores
        public ActionResult Index()
        {
            return View(data.ListaDeProveedores());
        }
    }
}

GSC/Controllers/TiketsController.cs
using BaseDeDatos;
using BaseDeDatos.Tikets;
using GSC.Models.Tikets;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GSC.Controllers
{
    public class TiketsController : Controller
    {
        TiketsData data = new TiketsData();
        // GET: Tikets
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CrearTiket()
        {
            var model = new CrearTiketsViewModel
            {
                listaPrioridad = this.GetTiposprioridad()
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult CrearTiket(CrearTiketsViewModel model)
        {
            var guarda = new Tickets
            {
                Usuario = model.Usuario,
                Email = model.Email,
                IdPreoridad = model.IdPreoridad,
                Telefono = model.Telefono,
                Problema = model.Problema,
                Descripcion = model.Descripcion,
                Fecha_Creacion = DateTime.Now,
                IdEstado = 1
            };

            data.GuardarTiket(guarda);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Gestionar()
        {
            var model = data.GetTikets().Select(s => new CrearTiketsViewModel
            {
                ID = s.ID,
                Usuario = s.Usuario,
                Email = s.Email,
                Problema = s.Problema,
                PrioridadNombre = s.Prioridad.Nombre
            }).ToList();
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult GestionarTiket(int id)
        {
            var infomacion = data.GetTiketPorId(id);
            var model = new CrearTiketsViewModel
            {
                Usuario = infomacion.Usuario,
                Email = infomacion.Email,
                IdPreoridad = infomacion.IdPreoridad,
                Telefono = infomacion.Telefono,
                Problema = infomacion.Problema,
                Descripcion = infomacion.Descripcion,
                Fecha_Creacion = infomacion.Fecha_Creacion,
                listaPrioridad = this.GetTiposprioridad(),
                listaEquipo = this.GetTDepartamentos()
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult GestionarTiket(CrearTiketsViewModel model)
        {
            var guardar = data.GetTiketPorId(model.ID);
            guardar.Usuario = model.Usuario;
            guardar.Email = model.Email;
            //guardar.IdPreoridad = model.IdPreoridad;
            guardar.Telefono = model.Telefono;
            guardar.Problema = model.Problema;
            guardar.Descripcion = model.Descripcion;
            guardar.Fecha_Entrega = model.Fecha_Entrega;
            guardar.IdEstado = 2;
            guardar.IdEquipoDepartamento = model.IdEquipoDepartamento;
            data.ActualizarTiket(guardar);
            return RedirectToAction("Gestionar");
        }

        [Authorize]
        public ActionResult ResolverTikets()
        {
            var model = data.GetTiketsEnProceso().Select(s => new CrearTiketsViewModel
            {
                ID = s.ID,
                Usuario = s.Usuario,
                Email = s.Email,
                Problema = s.Problema,
                PrioridadNombre = s.Prioridad.Nombre,
                Fecha_Entrega = s.Fecha_Entrega
            }).ToList();

            return View(model);
        }

        [Authorize]
        public ActionResult FinalizarTiket(int id)
        {
            var infomacion = data.GetTiketPorId(id);
            var model = new CrearTiketsViewModel
            {
                Usuario = infomacion.Usuario,
                Email = infomacion.Email,
                IdPreoridad = infomacion.IdPreoridad,
                Telefono = infomacion.Telefono,
                Problema = infomacion.Problema,
                Descripcion = infomacion.Descripcion,
                Fecha_Creacion = infomacion.Fecha_Creacion,
                Fecha_Entrega = infomacion.Fecha_Entrega,
            };

            return View(model);
        }

        [Authorize]
        public ActionResult EstadoTiketsTable()
        {
            var model = data.VerTiketsEstados().Select(s => new CrearTiketsViewModel
            {
                ID = s.ID,
                Usuario = s.Usuario,
                Email = s.Email,
                Problema = s.Problema,
                PrioridadNombre = s.Prioridad.Nombre,
                Fecha_Entrega = s.Fecha_Entrega,
                EstadoNombre = s.Estados.Nombre
            }).ToList();

            return View(model);
        }

        [Authorize]
        public ActionResult EstadoTiket(int id)
        {
            var infomacion = data.GetTiketConNotasPorId(id);
            var model = new CrearTiketsViewModel
            {
                Usuario = infomacion.Usuario,
                Email = infomacion.Email,
                IdPreoridad = infomacion.IdPreoridad,
                Telefono = infomacion.Telefono,
                Problema = infomacion.Problema,
                Descripcion = infomacion.Descripcion,
                Fecha_Creacion = infomacion.Fecha_Creacion,
                Fecha_Entrega = infomacion.Fecha_Entrega,
                Notas = infomacion.Notas.Select(s => new ListaNotasViewModel
                {
                    ID = s.ID,
                    IdTicket = s.IdTicket,
                    Nombre = s.Nombre,
                    Descripcion = s.Descripcion
                }).ToList()
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult EstadoTiket(CrearTiketsViewModel model)
        {
            var nota = new Notas
            {
                IdTicket = model.ID,
                Nombre = model.NombreNota,
                Descripcion = model.DescripcionNota
            };

            data.GuardarNota(nota);

            return RedirectToAction("EstadoTiket", new { model.ID });
        }

        [HttpPost]
        [Authorize]
        public ActionResult FinalizarTiket(CrearTiketsViewModel model)
        {
            var finalizar = data.GetTiketPorId(model.ID);
            finalizar.IdEstado = 4;
            data.FinalizarTiket(finalizar);
            return RedirectToAction("ResolverTikets");
        }


        private SelectList GetTiposprioridad()
        {
            return new SelectList(data.GetPrioridadList(), nameof(Prioridad.ID), nameof(Prioridad.Nombre));
        }

        private List<SelectListItem> GetTDepartamentos()
        {
            var model = data.GetDepartamentosList().Select(s => new SelectListItem 
            {
                Value = s.ID.ToString(),
                 Text = string.Format("{0} - {1}", s.Nombre, s.Departamentos.Nombre)
            }).ToList();

            return model;
        }
    }
}

GSC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GSC</title>
    <!-- plugins:css -->
    @Styles.Render("~/Content/css");
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/Content/assets/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" href="@Url.Action("Index","Home")"><img src="~/Content/assets/images/logo.svg" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="@Url.Action("Index","Home")"><img src="~/Content/assets/images/logo-mini.svg" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>
                @*<div class="search-field d-none d-md-block">
                        <form class="d-flex align-items-center h-100" action="#">
                            <div class="input-group">
                                <div class="input-group-prepend bg-transparent">
                                    <i class="input-group-text border-0 mdi mdi-magnify"></i>
                                </div>
                                <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
                            </div>
                        </form>
                    </div>*@
            <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item d-none d-lg-block full-screen-link">
                    <a class="nav-link">
                        <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                    </a>
                </li>
                <li class="nav-item nav-profile dropdown">
                    @Html.Partial("_LoginPartial")
                </li>
            </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            <span class="menu-title">Dashboard</span>
                            <i class="mdi mdi-home menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                            <span class="menu-title">Mantenimiento</span>
                            <i class="menu-arrow"></i>
                            <i class="mdi mdi-crosshairs-gps menu-icon"></i>
                        </a>
                        @*<div class="collapse" id="ui-basic">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index","Proveedores")">Proveedores</a></li>
                            </ul>
                        </div>*@
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Tikets")">
                            <span class="menu-title">Tickets</span>
                            <i class="mdi mdi-comment-text menu-icon"></i>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- partial -->
            @RenderBody()

            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    @Scripts.Render("~/Content/js");
</body>
</html>